services:
  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=scoreboard
      - MYSQL_ROOT_HOST=%

  website:
    image: website:final
    ports:
      - "80:80"
volumes:
  db_data:
