services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8001:5432"
    networks:
      - backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=super_secret_password
      
  api:
    build: ./backend/
    ports: 
      - "3000:3000"
    networks:
      - frontend
      - backend

  website:
    build: ./website/
    ports:
      - "8080:8080"
    networks:
      - frontend

volumes:
  database: {}

networks:
  frontend: {}
  backend: {}