services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/Users/ryan/ZEIT3118_db/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=scoreboard
      - MYSQL_ROOT_HOST=%

  website:
    build: ./website/
    ports:
      - "3000:3000"

volumes:
  db_data: {}
